name = "ActiveContours"
uuid = "2a096b4a-7755-4b95-b585-0f276b139faf"
authors = ["Dale <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
TestSetExtensions = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
